### ISSUE TITLE
Exception during processing - Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by Arhadrianman10** [camenduru/sdxl-colab#4]
Hello,

Im trying to execute the flow but i get an error, i dont know if im using the correct safetensor and refiner , and i am using drive to add the links of the models in the base and refiner fields and I don't know if this is correct. 

![image](https://github.com/camenduru/sdxl-colab/assets/86854034/724141ee-50ab-4e0c-b586-a1e121674437)

this is the log:

got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 145, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/ComfyUI/nodes.py", line 411, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "/content/ComfyUI/comfy/sd.py", line 1030, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "/content/ComfyUI/comfy/utils.py", line 9, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device="cpu")
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

Prompt executed in 0.00 seconds

thanks in advance

**Comment by camenduru** [comment]
HI @Arhadrianman10 👋 drive not direct link please use 

https://huggingface.co/stabilityai/stable-diffusion-xl-base-0.9/blob/main/sd_xl_base_0.9.safetensors
https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-0.9/blob/main/sd_xl_refiner_0.9.safetensors
